name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: false

  build_release:
    name: Build Release
    needs: create_release
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            release_file: dbt2pqt_linux
          - os: macos-latest
            release_file: dbt2pqt_mac
          - os: windows-latest
            release_file: dbt2pqt_win.exe
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Linux Build
        if: matrix.os == 'ubuntu-latest'
        run: cargo build --release && cp target/release/dbt2pqt dbt2pqt_linux
      
      - name: Run Mac Build
        if: matrix.os == 'macos-latest'
        run: cargo build --release && cp target/release/dbt2pqt dbt2pqt_mac

      - name: Run Windows Build
        if: matrix.os == 'windows-latest'
        run: cargo build --release && cp target/release/dbt2pqt.exe dbt2pqt_win.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create_release.outputs.tag-name }}
          files: ${{ matrix.release_file }}
